info:
  app:
    name: milepost-eureka-name
    description: 注册中心-des
    version: 1.0.0.100

server:
  #servlet:
    #context-path: /milepost-eureka
  port: 8761
#  port: 8762
#  port: 8763

spring:
  application:
    name: milepost-eureka
  profiles:
    active: prod
#  main:
#    banner-mode: console

eureka:
#  environment: abc
#  datacenter: dasf
  instance:
    #ip-address: 192.168.1.105
    ip-address: 172.16.1.208
#    ip-address: 192.168.186.5
#    ip-address: 192.168.243.1
#    prefer-ip-address: true
  client:
#    #禁止向自己注册自己
#    register-with-eureka: false
#    #禁止向注册中心检索服务列表
#    fetch-registry: false
    service-url:
      #单实例
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  server:
    enable-self-preservation: false
#      defaultZone: http://192.168.186.5:8762/eureka/,http://192.168.243.1:8763/eureka/
#      defaultZone: http://192.168.1.105:8761/eureka/,http://192.168.243.1:8763/eureka/
#      defaultZone: http://192.168.186.5:8762/eureka/,http://192.168.1.105:8761/eureka/
#  server:
#    renewal-threshold-update-interval-ms: 5000

#集群部署时候要开启，否则EurekaServer控制台的基本信息中显示副本不可达
#eureka.client.register-with-eureka: true
#eureka.client.fetch-registry: true

