info:
  app:
    name: 注册中心
    description: 注册中心
    version: 1.0.0.100

server:
  port: 8761

spring:
  application:
    name: milepost-eureka
  profiles:
    active: dev
  rabbitmq:
    #rabbitmq服务器ip
    host: 192.168.223.136
    #rabbitmq端口
    port: 5672
    #rabbitmq用户
    username: admin
    #rabbitmq密码
    password: admin
track:
  enabled: true
  sampling: 1

eureka:
  instance:
    ip-address: 192.168.223.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  server:
    enable-self-preservation: false