info:
  app:
    name: 注册中心
    description: 注册中心
    version: 1.0.0.100

server:
  port: 8761

spring:
  application:
    name: milepost-eureka
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.186.131
    port: 5672
    username: admin
    password: admin
track:
  sampling: 1

eureka:
  instance:
    ip-address: 192.168.186.5
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  server:
    enable-self-preservation: false