info:
  app:
    name: Turbine
    description: Turbine聚合监控本租户下的所有服务实例
    version: 1.0.0.100

server:
  port: 8769
  servlet:
    context-path: "/milepost-turbine"

spring:
  application:
    name: milepost-turbine
  profiles:
    active: dev
  rabbitmq:
    #rabbitmq服务器ip
    host: 192.168.186.131
    #rabbitmq端口
    port: 5672
    #rabbitmq用户
    username: admin
    #rabbitmq密码
    password: admin
track:
  enabled: true
  sampling: 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.186.5:8761/eureka/
  instance:
    ip-address: 192.168.186.5

multiple-tenant:
  tenant: tenant1

