info:
  app:
    name: Turbine监控
    description: Turbine监控
    version: 1.0.0.100

server:
  port: 8769
  servlet:
    context-path: "/milepost-turbine"

spring:
  application:
    name: milepost-turbine
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://192.168.223.129:8761/eureka/
  instance:
    ip-address: 192.168.223.1

multiple-tenant:
  tenant: tenant1

