info:
  app:
    name: JWT服务
    description: 发放JWT，提供身份认证支持
    version: 1.0.0.100

server:
  port: 9999
  servlet:
    context-path: "/milepost-auth"

spring:
  application:
    name: milepost-auth
  profiles:
    active: dev
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.186.131:3306/milepost_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: admin123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  rabbitmq:
    host: 192.168.186.131
    port: 5672
    username: admin
    password: admin
track:
  sampling: 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.186.5:8761/eureka/
  instance:
    ip-address: 192.168.186.5

multiple-tenant:
  tenant: tenant1
