server:
  port: 9998

spring:
  application:
    name: milepost-auth
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/milepost_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    jedis:
      pool:
        #配置连接池属性
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    #配置redis服务器属性
    database: 1
    host: 192.168.223.129
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
