info:
  app:
    name: JWT服务
    description: 发放JWT
    version: 1.0.0.100

server:
  port: 9999
  servlet:
    context-path: "/milepost-auth"

spring:
  application:
    name: milepost-auth
  profiles:
    active: dev
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.136:3306/milepost_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: admin123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  rabbitmq:
    #rabbitmq服务器ip
    host: 192.168.223.136
    #rabbitmq端口
    port: 5672
    #rabbitmq用户
    username: admin
    #rabbitmq密码
    password: admin
track:
  enabled: true
  sampling: 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.223.1:8761/eureka/
  instance:
    ip-address: 192.168.223.1

multiple-tenant:
  tenant: tenant1
  weight: 9
  label-and: aa,bb
  label-or: dd,ee,ff


#auth:
#  client-detail:
#    client-id: aaa
#    resource-ids: bbb
#    client-secret: ccc
#    scope: ddd
#    authorized-grant-types: eee
#    web-server-redirect-uri: fff
#    authorities: ggg
#    access-token-validity: 222
#    refresh-token-validity: 333
#    additional-information: fdas
#    autoapprove: true




