# 详细配置见https://codecentric.github.io/spring-boot-admin/2.1.0/#spring-boot-admin-server
info:
  app:
    name: Admin监控
    description: Admin监控
    version: 1.0.0.100

server:
  port: 8768
  #不支持设置context-path，前端请求时没有加context-path
#  servlet:
#    context-path: "/milepost-admin"

spring:
  application:
    name: milepost-admin
  profiles:
    active: dev
  rabbitmq:
    #rabbitmq服务器ip
    host: 192.168.223.136
    #rabbitmq端口
    port: 5672
    #rabbitmq用户
    username: admin
    #rabbitmq密码
    password: admin
#  mail:
#    username: m18310891237@163.com
#    password: sqm123456qweasd
#    host: smtp.163.com
#  boot:
#    admin:
#      notify:
#        mail:
#          enabled: true
          #from: Spring Boot Admin <${spring.mail.username}>
          #to: 969729588@qq.com
#  security:
#    user:
#      name: "admin"
#      password: "XSRF-TOKEN=random"
#  boot:
#    admin:
#      ui:
#        title: Milepost-Admin
#      instance-proxy:
#        # Headers not to be forwarded when making requests to clients。默认值[Cookie, Set-Cookie, Authorization]
#        ignored-headers: [Cookie, Set-Cookie, Authorization]
#      discovery:
#        # This services will be included when using discovery and registered as application. Supports simple patterns (e.g. "foo*", "*bar", "foo*bar*").
#        #services:
#        # This services will be ignored when using discovery and not registered as application. Supports simple patterns (e.g. "foo*", "*bar", "foo*bar*").
#        ignored-services: [Cookie, Set-Cookie, Authorization]
track:
  enabled: true
  sampling: 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.223.1:8761/eureka/
  instance:
    ip-address: 192.168.223.1
#    metadata-map:
#      user:
#        name: ${spring.security.user.name}
#        password: ${spring.security.user.password}

multiple-tenant:
  tenant: tenant1


##########
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
#logging:
#  level:
#    #禁止打印一个很长的warn
#    de.codecentric.boot.admin.server.services.EndpointDetectionTrigger: error
#    #禁止打印一个没影响的error
#    com.milepost.core.MilepostApplication: off



